version: '3.5'


services:
  jenkins:
    image: bauk/jenkins-master:$VERSION
    build: images/jenkins-master
    environment:
      - CASC_JENKINS_CONFIG=/jenkins.yaml
    configs:
      - source: jenkins
        target: /jenkins.yaml
    secrets:
      - source: SSH_SLAVE_KEY
        uid: '1000'
      - source: SSH_SLAVE_KEY_PASSWORD
        uid: '1000'
      - source: JENKINS_ADMIN_USER
        uid: '1000'
      - source: JENKINS_ADMIN_PASSWORD
        uid: '1000'
    ports:
      - 9000:8080
  jenkins_slave:
    image: bauk/jenkins-ssh_slave:$VERSION
    build:
      context: images/jenkins-ssh_slave
    environment:
      - SSH_USER=slave
      - SSH_USER_EXTRA_DIRS=/jenkins
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $PWD/tmp/slave_run:/run
    secrets:
      - source: SSH_SLAVE_PUBLIC_KEY
        target: SSH_PUBLIC_KEY
    deploy:
      replicas: 0
  jenkins_slave_docker:
    image: bauk/jenkins-ssh_slave-docker:$VERSION
    build:
      context: images/jenkins-ssh_slave-docker
      args:
        VERSION: ${VERSION}
    environment:
      - SSH_USER=slave
      - SSH_USER_EXTRA_DIRS=/jenkins
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $PWD/tmp/slave_run:/run
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: SSH_SLAVE_PUBLIC_KEY
        target: SSH_PUBLIC_KEY

  gerrit:
    image: gerritcodereview/gerrit:2.16.5
    configs:
      - source: gerrit
        target: /var/gerrit/etc/gerrit.config
    ports:
      - 29418:29418
      - 8080:8080
    # volumes:
    #   - gerrit-git:/var/gerrit/git
    #   - gerrit-db:/var/gerrit/db
    #   - gerrit-etc:/var/gerrit/etc
    #   - gerrit-cache:/var/gerrit/cache


  visualiser:
    image: dockersamples/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080

  # gitlab:
  #   image: store/gitlab/gitlab-ce:10.2.4-ce.0
  #   ports:
  #     - 1443:443
  #     - 1080:80
  #     - 1022:22

configs:
  jenkins:
    file: configs/jenkins.yaml
  gerrit:
    file: configs/gerrit.config

secrets:
  SSH_SLAVE_KEY:
    file: secrets/SSH_SLAVE_KEY
  SSH_SLAVE_KEY_PASSWORD:
    file: secrets/SSH_SLAVE_KEY_PASSWORD
  SSH_SLAVE_PUBLIC_KEY:
    file: secrets/SSH_SLAVE_PUBLIC_KEY
  JENKINS_ADMIN_USER:
    file: secrets/JENKINS_ADMIN_USER
  JENKINS_ADMIN_PASSWORD:
    file: secrets/JENKINS_ADMIN_PASSWORD

