version: '3.5'


services:
  jenkins:
    image: bauk/jenkins-master:$VERSION
    environment:
      - CASC_JENKINS_CONFIG=/jenkins.yaml
    configs:
      - source: jenkins
        target: /jenkins.yaml
    secrets:
      - source: SSH_SLAVE_KEY
        uid: '1000'
      - source: SSH_SLAVE_KEY_PASSWORD
        uid: '1000'
      - source: JENKINS_ADMIN_USER
        uid: '1000'
      - source: JENKINS_ADMIN_PASSWORD
        uid: '1000'
    ports:
      - 9000:8080
    deploy:
      replicas: 1
  jenkins_slave_docker:
    image: bauk/jenkins-ssh_slave-docker:$VERSION
    environment:
      - SSH_USER=slave
      - SSH_USER_EXTRA_DIRS=/jenkins
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $PWD/tmp/slave_run:/run
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - source: SSH_SLAVE_PUBLIC_KEY
        target: SSH_PUBLIC_KEY
    deploy:
      replicas: 0

  gerrit:
    image: bauk/gerrit-example:$VERSION
    configs:
      - source: gerrit
        target: /var/gerrit/etc/gerrit.config
    ports:
      - 29418:29418
      - 8080:8080
    deploy:
      replicas: 1
    # volumes:
    #   - gerrit-git:/var/gerrit/git
    #   - gerrit-db:/var/gerrit/db
    #   - gerrit-etc:/var/gerrit/etc
    #   - gerrit-cache:/var/gerrit/cache

  ldap:
    image: osixia/openldap:1.1.10
    command: --copy-service #--loglevel debug
    ports:
      - 389:389
#     - 636:636
    configs:
      - source: ldap
        target: /container/service/slapd/assets/config/bootstrap/ldif/custom/config.ldif
  ldapadmin:
    image: osixia/phpldapadmin
    ports:
      - 6443:443
      - 680:80
    environment:
     - PHPLDAPADMIN_LDAP_HOSTS=ldap
    depends_on:
      - ldap

  # gitlab:
  #   image: store/gitlab/gitlab-ce:10.2.4-ce.0
  #   ports:
  #     - 1443:443
  #     - 1080:80
  #     - 1022:22

configs:
  jenkins:
    file: configs/jenkins.yaml
  gerrit:
    file: configs/gerrit.config
  ldap:
    file: configs/ldap.ldif

secrets:
  SSH_SLAVE_KEY:
    file: secrets/SSH_SLAVE_KEY
  SSH_SLAVE_KEY_PASSWORD:
    file: secrets/SSH_SLAVE_KEY_PASSWORD
  SSH_SLAVE_PUBLIC_KEY:
    file: secrets/SSH_SLAVE_PUBLIC_KEY
  JENKINS_ADMIN_USER:
    file: secrets/JENKINS_ADMIN_USER
  JENKINS_ADMIN_PASSWORD:
    file: secrets/JENKINS_ADMIN_PASSWORD
  LDAP_PASSWORD:
    file: secrets/LDAP_PASSWORD

