version: '3.5'


services:
  jenkins:
    image: bauk/jenkins-master
    build: images/jenkins-master
    environment:
      - CASC_JENKINS_CONFIG=/jenkins.yaml
    volumes:
      - $PWD/jenkins.yaml:/jenkins.yaml
    secrets:
      - source: SSH_SLAVE_KEY
        uid: '1000'
      - source: SSH_SLAVE_KEY_PASSWORD
        uid: '1000'
      - source: JENKINS_ADMIN_USER
        uid: '1000'
      - source: JENKINS_ADMIN_PASSWORD
        uid: '1000'
    ports:
      - 9000:8080
  jenkins_slave:
    image: bauk/jenkins-ssh_slave
    build: images/jenkins-ssh_slave
    environment:
      - SSH_USER=slave
      - SSH_USER_EXTRA_DIRS=/jenkins
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $PWD/tmp/slave_run:/run
    ports:
      - 3022:22
    secrets:
      - source: SSH_SLAVE_PUBLIC_KEY
        target: SSH_PUBLIC_KEY
  jenkins_slave_docker:
    image: bauk/jenkins-ssh_slave-docker
    build: images/jenkins-ssh_slave-docker
    environment:
      - SSH_USER=slave
      - SSH_USER_ID=0 # Needs to be someone on host who has docker access
      - SSH_USER_EXTRA_DIRS=/jenkins
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $PWD/tmp/slave_run:/run
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4022:22
    secrets:
      - source: SSH_SLAVE_PUBLIC_KEY
        target: SSH_PUBLIC_KEY


  visualiser:
    image: dockersamples/visualizer


secrets:
  SSH_SLAVE_KEY:
    file: secrets/SSH_SLAVE_KEY
  SSH_SLAVE_KEY_PASSWORD:
    file: secrets/SSH_SLAVE_KEY_PASSWORD
  SSH_SLAVE_PUBLIC_KEY:
    file: secrets/SSH_SLAVE_PUBLIC_KEY
  JENKINS_ADMIN_USER:
    file: secrets/JENKINS_ADMIN_USER
  JENKINS_ADMIN_PASSWORD:
    file: secrets/JENKINS_ADMIN_PASSWORD

