version: '3.5'

services:
  jenkins:
    image: bauk/jenkins-full
    build: images/jenkins-full
    environment:
      - CASC_JENKINS_CONFIG=/jenkins.yaml
    volumes:
      - $PWD/jenkins.yaml:/jenkins.yaml
    secrets:
      - source: SSH_SLAVE_KEY
        uid: '1000'
      - source: SSH_SLAVE_KEY_PASSWORD
        uid: '1000'
    ports:
      - 9000:8080

  visualiser:
    image: dockersamples/visualizer

secrets:
  SSH_SLAVE_KEY:
    file: secrets/SSH_SLAVE_KEY
  SSH_SLAVE_KEY_PASSWORD:
    file: secrets/SSH_SLAVE_KEY_PASSWORD
